Chapter 3 Exercises - Questions 8, 9
================

-   [Question 8](#question-8)
    -   [Part 8a](#part-8a)
    -   [Part 8b](#part-8b)
    -   [Part 8c](#part-8c)
-   [Question 9](#question-9)
    -   [Part 9a](#part-9a)
    -   [Part 9b](#part-9b)
    -   [Part 9c](#part-9c)
    -   [Part 9d](#part-9d)
    -   [Part 9e (in progress)](#part-9e-in-progress)
    -   [Part 9f (in progress)](#part-9f-in-progress)

Question 8
----------

*This question involves the use of simple linear regression on the `Auto` data set.*

We start off by loading the data and taking a look at its structure:

``` r
data("Auto")
names(Auto)
```

    ## [1] "mpg"          "cylinders"    "displacement" "horsepower"  
    ## [5] "weight"       "acceleration" "year"         "origin"      
    ## [9] "name"

``` r
str(Auto)
```

    ## 'data.frame':    392 obs. of  9 variables:
    ##  $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
    ##  $ cylinders   : num  8 8 8 8 8 8 8 8 8 8 ...
    ##  $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
    ##  $ horsepower  : num  130 165 150 150 140 198 220 215 225 190 ...
    ##  $ weight      : num  3504 3693 3436 3433 3449 ...
    ##  $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
    ##  $ year        : num  70 70 70 70 70 70 70 70 70 70 ...
    ##  $ origin      : num  1 1 1 1 1 1 1 1 1 1 ...
    ##  $ name        : Factor w/ 304 levels "amc ambassador brougham",..: 49 36 231 14 161 141 54 223 241 2 ...

### Part 8a

*Use the `lm()` function to perform a simple linear regression with mpg as the response and horsepower as the predictor. Use the `summary()` function to print the results. Comment on the output.*

``` r
mpg_hp_lm <- lm(mpg ~ horsepower, data = Auto)
summary(mpg_hp_lm)
```

    ## 
    ## Call:
    ## lm(formula = mpg ~ horsepower, data = Auto)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -13.5710  -3.2592  -0.3435   2.7630  16.9240 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 39.935861   0.717499   55.66   <2e-16 ***
    ## horsepower  -0.157845   0.006446  -24.49   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 4.906 on 390 degrees of freedom
    ## Multiple R-squared:  0.6059, Adjusted R-squared:  0.6049 
    ## F-statistic: 599.7 on 1 and 390 DF,  p-value: < 2.2e-16

*For example:*

1.  *Is there a relationship between the predictor and the response?*
2.  *How strong is the relationship between the predictor and the response?*
3.  *Is the relationship between the predictor and the response positive or negative?*
4.  *What is the predicted mpg associated with a horsepower of 98? What are the associated 95% confidence and prediction intervals?*

The relation between the predictor `horsepower` and response `mpg` is negative, as shown by the estimated coefficient **-0.1578447** which is less than 0.

Based on the output generated by the linear model, the p-value associated with the coefficient for `horsepower` is extremely low. We can conclude that there is a **significant negative** relationship between `horsepower` and `mpg`.

The strength of the relationship between `horsepower` and `mpg` is indicated by the *Pearson correlation coefficient*. For a simple linear regression model, the correlation coefficient can be found by taking the *negative* square root (since the linear coefficient is negative) of the Multiple R-squared value in the output:

``` r
-sqrt(summary(mpg_hp_lm)$r.squared)
```

    ## [1] -0.7784268

Alternatively, the correlation coefficient can be found using the `cor()` function:

``` r
cor(Auto$mpg, Auto$horsepower)
```

    ## [1] -0.7784268

The magnitude of the correlation coefficient suggests a **moderately strong relationship** between `horsepower` and `mpg`.

We can find out the predicted values of `mpg` and their intervals using the `predict()` function.
The following code attempts to predict `mpg` and the 95% confidence intervals for a given set of `horsepower` values:

``` r
predict(mpg_hp_lm, newdata = data.frame(horsepower = 98), 
        interval = "confidence")
```

    ##        fit      lwr      upr
    ## 1 24.46708 23.97308 24.96108

We change the `interval` parameter if we want to calculate the 95% *prediction* intervals:

``` r
predict(mpg_hp_lm, newdata = data.frame(horsepower = 98), 
        interval = "prediction")
```

    ##        fit     lwr      upr
    ## 1 24.46708 14.8094 34.12476

Based on the output, for `horsepower` of 98, the predicted `mpg` value would be about **24.47** (miles per gallon); the 95% confidence interval would be approximately **(23.97, 24.96)** and the 95% prediction interval would be approximately **(14.81, 34.12)**.
(The confidence interval reflects the uncertainty surrounding the predicted `mpg` averaged over multiple vehicles; the prediction interval reflects the uncertainty surrounding the `mpg` predicted for a particular vehicle, which also takes into the account the irreducible error ϵ.)

### Part 8b

*Plot the response and the predictor. Use the `abline()` function to display the least squares regression line.*

``` r
plot(mpg ~ horsepower, data = Auto, pch = 1, cex = 0.6,
     main = "Miles per gallon against Horsepower",
     xlab = "Engine Horsepower", ylab = "Miles per Gallon")
abline(mpg_hp_lm)
```

![](chapter3_q8q9_files/figure-markdown_github-ascii_identifiers/q8%20plot-1.png)

### Part 8c

*Use the `plot()` function to produce diagnostic plots of the least squares regression fit. Comment on any problems you see with the fit.*

``` r
par(mfrow = c(2,2))
plot(mpg_hp_lm)
```

![](chapter3_q8q9_files/figure-markdown_github-ascii_identifiers/q8%20diagnostic%20plot-1.png)

A brief description of the diagnostic plots shown above:

-   The top-left plot is a residual plot, which plots the residuals *e<sub>i</sub> = y<sub>i</sub> - ŷ<sub>i</sub>* against the fitted values.
-   The top-right plot is a quantile-quantile plot (QQ plot) of the residuals to check if the residuals are normally distributed.
-   The bottom-left plot is a scale-location plot that examines if residuals are spread equally along the range of predictors and can be used to check the assumption of equal variance (homoscedascity).
-   The bottom-right plot is a plot of residuals against leverage, to check for outliers with significant leverage that would heavily influence the regression model.

From the diagnostic plots, we can see the following issues:

-   The plot of residuals against fitted values appear to exhibit a pattern which suggests that our linear model is not a good fit for the relationship between `horsepower` and `mpg`: the pattern in the residuals may be due to a non-linear relationship that the model does not capture.
-   The response-predictor plot generated in (b) suggests that the relationship between `mpg` and `horsepower` may not be linear; the rate of change in `mpg` decreases as `horsepower` increases, so a reciprocal function might produce a better fit.

Question 9
----------

This question involves the use of multiple linear regression on the `Auto` data set.

### Part 9a

*Produce a scatterplot matrix which includes all of the variables in the data set.*

``` r
plot(Auto)
```

![](chapter3_q8q9_files/figure-markdown_github-ascii_identifiers/q9%20scatterplot-1.png)

### Part 9b

*Compute the matrix of correlations between the variables using the function `cor()`. You will need to exclude the `name` variable, which is qualitative.*

``` r
auto_noname <- Auto[, -9] # new data frame that excludes name variable (9th column)
signif(cor(auto_noname), 4)
```

    ##                  mpg cylinders displacement horsepower  weight
    ## mpg           1.0000   -0.7776      -0.8051    -0.7784 -0.8322
    ## cylinders    -0.7776    1.0000       0.9508     0.8430  0.8975
    ## displacement -0.8051    0.9508       1.0000     0.8973  0.9330
    ## horsepower   -0.7784    0.8430       0.8973     1.0000  0.8645
    ## weight       -0.8322    0.8975       0.9330     0.8645  1.0000
    ## acceleration  0.4233   -0.5047      -0.5438    -0.6892 -0.4168
    ## year          0.5805   -0.3456      -0.3699    -0.4164 -0.3091
    ## origin        0.5652   -0.5689      -0.6145    -0.4552 -0.5850
    ##              acceleration    year  origin
    ## mpg                0.4233  0.5805  0.5652
    ## cylinders         -0.5047 -0.3456 -0.5689
    ## displacement      -0.5438 -0.3699 -0.6145
    ## horsepower        -0.6892 -0.4164 -0.4552
    ## weight            -0.4168 -0.3091 -0.5850
    ## acceleration       1.0000  0.2903  0.2127
    ## year               0.2903  1.0000  0.1815
    ## origin             0.2127  0.1815  1.0000

### Part 9c

*Use the `lm()` function to perform a multiple linear regression with mpg as the response and all other variables except name as the predictors. Use the `summary()` function to print the results.*

``` r
auto_multiple_lm <- lm(mpg ~ ., data = auto_noname)
(auto_mlm_summary <- summary(auto_multiple_lm)) # assigns and prints the summary
```

    ## 
    ## Call:
    ## lm(formula = mpg ~ ., data = auto_noname)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -9.5903 -2.1565 -0.1169  1.8690 13.0604 
    ## 
    ## Coefficients:
    ##                Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)  -17.218435   4.644294  -3.707  0.00024 ***
    ## cylinders     -0.493376   0.323282  -1.526  0.12780    
    ## displacement   0.019896   0.007515   2.647  0.00844 ** 
    ## horsepower    -0.016951   0.013787  -1.230  0.21963    
    ## weight        -0.006474   0.000652  -9.929  < 2e-16 ***
    ## acceleration   0.080576   0.098845   0.815  0.41548    
    ## year           0.750773   0.050973  14.729  < 2e-16 ***
    ## origin         1.426141   0.278136   5.127 4.67e-07 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 3.328 on 384 degrees of freedom
    ## Multiple R-squared:  0.8215, Adjusted R-squared:  0.8182 
    ## F-statistic: 252.4 on 7 and 384 DF,  p-value: < 2.2e-16

Comment on the output. For instance:

1.  Is there a relationship between the predictors and the response?
2.  Which predictors appear to have a statistically significant relationship to the response?
3.  What does the coefficient for the year variable suggest?

The F-statistic for the overall model is very high, suggesting that there is a relationship between the predictors and the response (rejecting the null hypothesis that all of the predictors are not related to the response)

Based on the p-values for the t-statistic, we think the following predictors may have a statistically significant relationship with the response:

-   `displacement`
-   `weight`
-   `year`
-   `origin`

The coefficient for `year` is 0.751, which implies that the average miles per gallon increases by this amount every year when all other predictors are held constant.

### Part 9d

*Use the `plot()` function to produce diagnostic plots of the linear regression fit. Comment on any problems you see with the fit. Do the residual plots suggest any unusually large outliers? Does the leverage plot identify any observations with unusually high leverage?*

``` r
par(mfrow = c(2,2))
plot(auto_multiple_lm)
```

![](chapter3_q8q9_files/figure-markdown_github-ascii_identifiers/q9%20diagnostic%20plot-1.png)

-   The residuals-fitted plot shows a slight pattern which suggests the presence of relationships not accounted for by our model (such as non-linear predictors).
-   There are some observations with particularly large residuals (especially index 327 which is marked on all four plots).
-   Index 14 is a high-leverage observation but the residual is not considered significant enough to severely influence the regression model.

### Part 9e (in progress)

*Use the `\*` and `:` symbols to fit linear regression models with interaction effects. Do any interactions appear to be statistically significant?*

For example, we may want to find out if there may be a significant interaction between `displacement` and `horsepower` (in other words, does the relationship between `displacement` and `mpg` change depending on the `horsepower` of the vehicle?) We use the `update()` and `summary()` functions to refit the model:

``` r
summary(
    update(auto_multiple_lm, ~ . + displacement:weight)
    )
```

    ## 
    ## Call:
    ## lm(formula = mpg ~ cylinders + displacement + horsepower + weight + 
    ##     acceleration + year + origin + displacement:weight, data = auto_noname)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -9.9027 -1.8092 -0.0946  1.5549 12.1687 
    ## 
    ## Coefficients:
    ##                       Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)         -5.389e+00  4.301e+00  -1.253   0.2109    
    ## cylinders            1.175e-01  2.943e-01   0.399   0.6899    
    ## displacement        -6.837e-02  1.104e-02  -6.193 1.52e-09 ***
    ## horsepower          -3.280e-02  1.238e-02  -2.649   0.0084 ** 
    ## weight              -1.064e-02  7.136e-04 -14.915  < 2e-16 ***
    ## acceleration         6.724e-02  8.805e-02   0.764   0.4455    
    ## year                 7.852e-01  4.553e-02  17.246  < 2e-16 ***
    ## origin               5.610e-01  2.622e-01   2.139   0.0331 *  
    ## displacement:weight  2.269e-05  2.257e-06  10.054  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 2.964 on 383 degrees of freedom
    ## Multiple R-squared:  0.8588, Adjusted R-squared:  0.8558 
    ## F-statistic: 291.1 on 8 and 383 DF,  p-value: < 2.2e-16

The interaction term `displacement:weight` appears to be significant based on its p-value; in addition the R-squared value has also risen by about .04, which suggests that our new model might be a slightly better fit than the model used in Part 9c.

It's also worth noting that `horsepower` itself is also now a significant predictor.

Fitting various interaction effects into the model yields the following p-values, as well as their respective model fit:

    ##                         cylinders displacement horsepower    weight
    ## displacement:horsepower   0.03275    2.795e-11  8.858e-20 1.710e-06
    ## displacement:weight       0.68990    1.521e-09  8.404e-03 5.491e-40
    ## displacement:year         0.96950    8.780e-13  1.559e-02 3.870e-19
    ## displacement:origin       0.14060    1.172e-04  2.659e-01 3.657e-17
    ## horsepower:weight         0.91840    3.786e-01  2.389e-20 5.793e-42
    ## horsepower:year           0.78800    4.640e-01  4.334e-16 1.420e-16
    ## horsepower:origin         0.08226    8.452e-01  1.378e-05 3.520e-12
    ## weight:year               0.68810    6.629e-02  2.591e-02 1.942e-10
    ## weight:origin             0.06820    2.588e-01  4.321e-01 1.065e-02
    ## year:origin               0.11510    3.806e-02  3.058e-01 1.485e-20
    ##                         acceleration      year    origin interaction   RSE
    ## displacement:horsepower      0.01921 9.949e-47 6.683e-03   3.387e-24 2.912
    ## displacement:weight          0.44550 9.824e-50 3.306e-02   2.928e-21 2.964
    ## displacement:year            0.25680 1.222e-35 4.337e-06   1.247e-11 3.138
    ## displacement:origin          0.64290 9.224e-41 1.759e-05   4.383e-03 3.297
    ## horsepower:weight            0.30910 3.244e-49 9.858e-04   4.119e-23 2.931
    ## horsepower:year              0.75120 8.524e-36 5.655e-06   6.663e-17 3.042
    ## horsepower:origin            0.24340 1.085e-41 1.092e-16   8.442e-13 3.116
    ## weight:year                  0.11640 1.649e-28 8.297e-06   1.473e-14 3.084
    ## weight:origin                0.69890 1.875e-41 2.604e-07   3.114e-05 3.257
    ## year:origin                  0.34750 2.263e-04 2.978e-03   1.064e-03 3.286
    ##                            rsq adj_rsq
    ## displacement:horsepower 0.8636  0.8608
    ## displacement:weight     0.8588  0.8558
    ## displacement:year       0.8417  0.8384
    ## displacement:origin     0.8252  0.8216
    ## horsepower:weight       0.8618  0.8590
    ## horsepower:year         0.8512  0.8481
    ## horsepower:origin       0.8438  0.8406
    ## weight:year             0.8470  0.8439
    ## weight:origin           0.8294  0.8258
    ## year:origin             0.8264  0.8228

<!-- test combinations of one interaction term, then spread the table -->
### Part 9f (in progress)

*Try a few different transformations of the variables, such as log(X), √X, X<sup>2</sup> . Comment on your findings.*

We can refit the model with a quadratic transformation term `horsepower^2^` to observe the fit of the new model:

``` r
summary(
    update(auto_multiple_lm, ~ . + I(horsepower^2))
    )
```

    ## 
    ## Call:
    ## lm(formula = mpg ~ cylinders + displacement + horsepower + weight + 
    ##     acceleration + year + origin + I(horsepower^2), data = auto_noname)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -8.5497 -1.7311 -0.2236  1.5877 11.9955 
    ## 
    ## Coefficients:
    ##                   Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)      1.3236564  4.6247696   0.286 0.774872    
    ## cylinders        0.3489063  0.3048310   1.145 0.253094    
    ## displacement    -0.0075649  0.0073733  -1.026 0.305550    
    ## horsepower      -0.3194633  0.0343447  -9.302  < 2e-16 ***
    ## weight          -0.0032712  0.0006787  -4.820 2.07e-06 ***
    ## acceleration    -0.3305981  0.0991849  -3.333 0.000942 ***
    ## year             0.7353414  0.0459918  15.989  < 2e-16 ***
    ## origin           1.0144130  0.2545545   3.985 8.08e-05 ***
    ## I(horsepower^2)  0.0010060  0.0001065   9.449  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 3.001 on 383 degrees of freedom
    ## Multiple R-squared:  0.8552, Adjusted R-squared:  0.8522 
    ## F-statistic: 282.8 on 8 and 383 DF,  p-value: < 2.2e-16

The transformed predictor appears to be significant as well, with the R-squared value increasing by about 0.3.
